language: java

build: trusty

jdk:
- oraclejdk8

git:
  quiet: true

before_script:
- cd /usr/share
- sudo mkdir chromedriver
- sudo wget https://chromedriver.storage.googleapis.com/2.44/chromedriver_linux64.zip
- unzip -y chromedriver_linux64.zip 


addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-beta

install: true

script: 
- mvn clean install -U
- mvn dependency::tree
- mvn clean test
- mvn -f pom.xml test


after_failure:
- cat target/surefire-reports/*.txt
